/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.orioninc.queueservice.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AgentSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8315477227783029554L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AgentSchema\",\"namespace\":\"com.orioninc.queueservice.avro\",\"fields\":[{\"name\":\"requestType\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"status\",\"type\":\"boolean\",\"default\":false},{\"name\":\"skill\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AgentSchema> ENCODER =
      new BinaryMessageEncoder<AgentSchema>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AgentSchema> DECODER =
      new BinaryMessageDecoder<AgentSchema>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AgentSchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AgentSchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AgentSchema>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AgentSchema to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AgentSchema from a ByteBuffer. */
  public static AgentSchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence requestType;
  @Deprecated public long id;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public boolean status;
  @Deprecated public java.lang.CharSequence skill;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AgentSchema() {}

  /**
   * All-args constructor.
   * @param requestType The new value for requestType
   * @param id The new value for id
   * @param name The new value for name
   * @param status The new value for status
   * @param skill The new value for skill
   */
  public AgentSchema(java.lang.CharSequence requestType, java.lang.Long id, java.lang.CharSequence name, java.lang.Boolean status, java.lang.CharSequence skill) {
    this.requestType = requestType;
    this.id = id;
    this.name = name;
    this.status = status;
    this.skill = skill;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return requestType;
    case 1: return id;
    case 2: return name;
    case 3: return status;
    case 4: return skill;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: requestType = (java.lang.CharSequence)value$; break;
    case 1: id = (java.lang.Long)value$; break;
    case 2: name = (java.lang.CharSequence)value$; break;
    case 3: status = (java.lang.Boolean)value$; break;
    case 4: skill = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'requestType' field.
   * @return The value of the 'requestType' field.
   */
  public java.lang.CharSequence getRequestType() {
    return requestType;
  }

  /**
   * Sets the value of the 'requestType' field.
   * @param value the value to set.
   */
  public void setRequestType(java.lang.CharSequence value) {
    this.requestType = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.Boolean getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.Boolean value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'skill' field.
   * @return The value of the 'skill' field.
   */
  public java.lang.CharSequence getSkill() {
    return skill;
  }

  /**
   * Sets the value of the 'skill' field.
   * @param value the value to set.
   */
  public void setSkill(java.lang.CharSequence value) {
    this.skill = value;
  }

  /**
   * Creates a new AgentSchema RecordBuilder.
   * @return A new AgentSchema RecordBuilder
   */
  public static com.orioninc.queueservice.avro.AgentSchema.Builder newBuilder() {
    return new com.orioninc.queueservice.avro.AgentSchema.Builder();
  }

  /**
   * Creates a new AgentSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AgentSchema RecordBuilder
   */
  public static com.orioninc.queueservice.avro.AgentSchema.Builder newBuilder(com.orioninc.queueservice.avro.AgentSchema.Builder other) {
    return new com.orioninc.queueservice.avro.AgentSchema.Builder(other);
  }

  /**
   * Creates a new AgentSchema RecordBuilder by copying an existing AgentSchema instance.
   * @param other The existing instance to copy.
   * @return A new AgentSchema RecordBuilder
   */
  public static com.orioninc.queueservice.avro.AgentSchema.Builder newBuilder(com.orioninc.queueservice.avro.AgentSchema other) {
    return new com.orioninc.queueservice.avro.AgentSchema.Builder(other);
  }

  /**
   * RecordBuilder for AgentSchema instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AgentSchema>
    implements org.apache.avro.data.RecordBuilder<AgentSchema> {

    private java.lang.CharSequence requestType;
    private long id;
    private java.lang.CharSequence name;
    private boolean status;
    private java.lang.CharSequence skill;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.orioninc.queueservice.avro.AgentSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.requestType)) {
        this.requestType = data().deepCopy(fields()[0].schema(), other.requestType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.skill)) {
        this.skill = data().deepCopy(fields()[4].schema(), other.skill);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AgentSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(com.orioninc.queueservice.avro.AgentSchema other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.requestType)) {
        this.requestType = data().deepCopy(fields()[0].schema(), other.requestType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.skill)) {
        this.skill = data().deepCopy(fields()[4].schema(), other.skill);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'requestType' field.
      * @return The value.
      */
    public java.lang.CharSequence getRequestType() {
      return requestType;
    }

    /**
      * Sets the value of the 'requestType' field.
      * @param value The value of 'requestType'.
      * @return This builder.
      */
    public com.orioninc.queueservice.avro.AgentSchema.Builder setRequestType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.requestType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'requestType' field has been set.
      * @return True if the 'requestType' field has been set, false otherwise.
      */
    public boolean hasRequestType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'requestType' field.
      * @return This builder.
      */
    public com.orioninc.queueservice.avro.AgentSchema.Builder clearRequestType() {
      requestType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.orioninc.queueservice.avro.AgentSchema.Builder setId(long value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.orioninc.queueservice.avro.AgentSchema.Builder clearId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.orioninc.queueservice.avro.AgentSchema.Builder setName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.orioninc.queueservice.avro.AgentSchema.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.Boolean getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.orioninc.queueservice.avro.AgentSchema.Builder setStatus(boolean value) {
      validate(fields()[3], value);
      this.status = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.orioninc.queueservice.avro.AgentSchema.Builder clearStatus() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'skill' field.
      * @return The value.
      */
    public java.lang.CharSequence getSkill() {
      return skill;
    }

    /**
      * Sets the value of the 'skill' field.
      * @param value The value of 'skill'.
      * @return This builder.
      */
    public com.orioninc.queueservice.avro.AgentSchema.Builder setSkill(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.skill = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'skill' field has been set.
      * @return True if the 'skill' field has been set, false otherwise.
      */
    public boolean hasSkill() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'skill' field.
      * @return This builder.
      */
    public com.orioninc.queueservice.avro.AgentSchema.Builder clearSkill() {
      skill = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AgentSchema build() {
      try {
        AgentSchema record = new AgentSchema();
        record.requestType = fieldSetFlags()[0] ? this.requestType : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.Long) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.status = fieldSetFlags()[3] ? this.status : (java.lang.Boolean) defaultValue(fields()[3]);
        record.skill = fieldSetFlags()[4] ? this.skill : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AgentSchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<AgentSchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AgentSchema>
    READER$ = (org.apache.avro.io.DatumReader<AgentSchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
